### ISSUE TITLE
Missing checksum comparison

### ISSUE THREAD

**Issue by fnoks** [uvasoftware/scanii-token-sample#1]
I don't understand how this example makes sure the file being scanned is the same file as the one being uploaded to the /process endpoint?

I see, though, that your API returns the SHA1 checksum for each file that has been scanned. If your example backend created a checksum for the uploaded file and compared it to the checksum from your API, it should be safe. Do you agree?

**Comment by rferreira** [comment]
Yup that would be a good improvement and it would cover for the case in which a file is modified/tempered in transit. I'll keep this ticket open until we can push a PR for it. Thanks!
